name = "y-gui"
main = "src/index.ts"
compatibility_date = "2024-03-05"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[assets]
directory = "../frontend/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"


[[kv_namespaces]]
binding = "USER_KV"
id = "e4110deae3dd4f01b328ba80f43a00cd"
preview_id = "e4110deae3dd4f01b328ba80f43a00cd"

# Development settings
[dev]
port = 8787
ip = "localhost"
local_protocol = "http"

# Enable logging
[observability]
enabled = true
head_sampling_rate = 1

# Default configuration for bots and MCP servers
[vars]
BOTS = '[{"name":"local-deepseek","model":"deepseek-r1:7b","base_url":"http://localhost:11434","api_key":"local-key","mcp_servers":["default"],"custom_api_path":"/v1/chat/completions","api_type":"local-key"}]'
MCP_SERVERS = '[{"name":"default","url":"http://localhost:3000/mcp","token":null,"need_confirm":null}]'

# Scheduled tasks
[triggers]
crons = ["0 * * * *"]  # Run every hour

