name = "y-gui"
main = "src/index.ts"
compatibility_date = "2024-03-05"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[assets]
directory = "../frontend/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[r2_buckets]]
binding = "CHAT_R2"
bucket_name = "mcp"
preview_bucket_name = "mcp"

[[kv_namespaces]]
binding = "USER_KV"
id = "e4110deae3dd4f01b328ba80f43a00cd"
preview_id = "e4110deae3dd4f01b328ba80f43a00cd"

# Development settings
[dev]
port = 8787
ip = "localhost"
local_protocol = "http"

# Enable logging
[observability]
enabled = true
head_sampling_rate = 1

# Scheduled tasks
[triggers]
crons = ["0 * * * *"]  # Run every hour

# D1 Database
[[d1_databases]]
binding = "CHAT_DB"
database_name = "yovy"
database_id = "bd822d41-bee0-4736-b048-1cabe7447dcf" # Replace with your actual database ID
